development:
  sessions:
    default:
      database: cms
      hosts:
        - localhost:27017
production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ<em>URL'] %>
      options:
        skip_version_check: true
        safe: true